name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v4
          with:
            branches: |
                [
                '+([0-9])?(.{+([0-9]),x}).x',
                'master',
                'next',
                'next-major',
                {
                    name: 'beta',
                    prerelease: true
                },
                {
                    name: 'alpha',
                    prerelease: true
                }
                ]
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

